### ISSUE TITLE
Chaning GPL to LGPL (or any other less restrictive license)?

### ISSUE THREAD

**Issue by aminya** [UMSATS/cdh-tsat5#8]
Choosing GPL as license makes it unlinkable with other projects/subsystems.

**Comment by rahmant3** [comment]
@aminya, I agree with switching to LGPL. This would be a good time to do it, as both me and @joehowarth17 are the sole contributors. As long as both myself and @joehowarth17 are in agreement, it should be fine. Future revisions of this repository will be LGPL. GPL doesn't make it unlinkable, but if other projects/subsystems are distributed with linked binaries, they must be also under GPL. So only changes to another "CDH" platform would have to be released under GPL.

Will have time sometime next week to change it (still need to merge MRAM software to master).

**Comment by rahmant3** [comment]
Switching to MIT instead. LGPL appears to only apply to statically linked binaries (e.g. libraries like .a files), which this project will not provide.

**Comment by aminya** [comment]
Yes! that would be awesome

**Comment by rahmant3** [comment]
PR has been merged. Closing issue.
